# Generated by Django 5.2.8 on 2025-11-10 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicalEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "quantity_available",
                    models.IntegerField(default=0, verbose_name="Quantité disponible"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Matériel Médical",
                "verbose_name_plural": "Matériels Médicaux",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("date_of_birth", models.DateField(verbose_name="Date de naissance")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin"), ("O", "Autre")],
                        max_length=1,
                        verbose_name="Sexe",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        verbose_name="Groupe sanguin",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                ("address", models.TextField(verbose_name="Adresse")),
                (
                    "medical_history",
                    models.TextField(
                        blank=True, null=True, verbose_name="Antécédents médicaux"
                    ),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, null=True, verbose_name="Allergies"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Surgeon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "specialty",
                    models.CharField(max_length=200, verbose_name="Spécialité"),
                ),
                (
                    "license_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de licence"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "years_of_experience",
                    models.IntegerField(default=0, verbose_name="Années d'expérience"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chirurgien",
                "verbose_name_plural": "Chirurgiens",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Surgery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "procedure_type",
                    models.CharField(
                        max_length=200, verbose_name="Type d'intervention"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("scheduled_date", models.DateTimeField(verbose_name="Date prévue")),
                (
                    "actual_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Heure de début réelle"
                    ),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Heure de fin réelle"
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        help_text="Durée estimée en minutes",
                        verbose_name="Durée estimée (min)",
                    ),
                ),
                (
                    "operating_room",
                    models.CharField(max_length=50, verbose_name="Salle d'opération"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En Attente"),
                            ("scheduled", "Planifié"),
                            ("in_progress", "En Cours"),
                            ("completed", "Terminé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("elective", "Programmée"),
                            ("urgent", "Urgente"),
                            ("emergency", "Urgence vitale"),
                        ],
                        default="elective",
                        max_length=20,
                        verbose_name="Urgence",
                    ),
                ),
                (
                    "pre_operative_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notes pré-opératoires"
                    ),
                ),
                (
                    "post_operative_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notes post-opératoires"
                    ),
                ),
                (
                    "complications",
                    models.TextField(
                        blank=True, null=True, verbose_name="Complications"
                    ),
                ),
                (
                    "anesthesia_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Type d'anesthésie",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surgeries",
                        to="surgical_tracker.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "surgeon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surgeries",
                        to="surgical_tracker.surgeon",
                        verbose_name="Chirurgien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme Chirurgical",
                "verbose_name_plural": "Programmes Chirurgicaux",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_surgery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="surgical_tracker.surgery",
                        verbose_name="Chirurgie associée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité",
                "verbose_name_plural": "Activités",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurgeryEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_used",
                    models.IntegerField(default=1, verbose_name="Quantité utilisée"),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surgical_tracker.medicalequipment",
                        verbose_name="Matériel",
                    ),
                ),
                (
                    "surgery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="surgical_tracker.surgery",
                        verbose_name="Chirurgie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matériel pour Chirurgie",
                "verbose_name_plural": "Matériels pour Chirurgie",
                "unique_together": {("surgery", "equipment")},
            },
        ),
    ]
