# Generated by Django 4.2.7 on 2023-11-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full time', 'part time'), ('part time', 'full time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
